# dbt_project.yml

name: 'paid_ads_mcdm'
version: '1.0.0'
config-version: 2

# Must match the profile name in your profiles.yml
profile: 'paid_ads_mcdm'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  paid_ads_mcdm:
    mcdm:
      +materialized: table
